### PR TITLE
Jacoco

### PR DESCRIPTION
**Pull request by muhammad83**
add code coverage

### CODE REVIEW

**Comment by abendt** [comment]
I see you closed it. Whats the status of this?

**Comment by muhammad83** [comment]
its not working at all so I thought PR is not the right step at the min. I am trying to figure out why its not working. Don't have a ETA of how long it will take but i have found another resource i am trying now so hopefully by the end of today

**Comment by abendt** [comment]
> its not working at all so I thought PR is not the right step at the min. 

ok, got it. one nice github feature is a DRAFT PR. however this is not available here as this is a private + free account. think its only available in paid or public repos.

> I am trying to figure out why its not working. 

if you get stuck feel free to ask. happy to help

**Comment by muhammad83** [comment]
i had to make this into a public repo as github actions were not being offered on the private one.

**Comment by abendt** [comment]
Are you sure about that? I think i have at least one private repo that uses gh actions. 

Shouldn't be a problem to convert this to public but what problems did you run into?

**Pull request closed without merging**
